name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    outputs:
      exe-path: ${{ steps.build-release.outputs.exe-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release
        id: build-release
        run: |
          cargo build --release
          echo "exe-path=target/release/windbgmsg.exe" >> $GITHUB_OUTPUT

      - name: Upload release executable
        uses: actions/upload-artifact@v4
        with:
          name: windbgmsg-exe
          path: target/release/windbgmsg.exe

  release:
    if: github.event_name == 'release'
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: windbgmsg-exe
          path: .

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: windbgmsg.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
