name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release
        run: cargo build --release

      - name: Upload release executable
        uses: actions/upload-artifact@v4
        with:
          name: windbgmsg-exe
          path: target/release/windbgmsg.exe

  release:
    if: github.event_name == 'release'
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release
        run: cargo build --release

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/windbgmsg.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
